AllCops:
  TargetRubyVersion: 3.1
  NewCops: disable
  Exclude:
    - 'vendor/**/*'

Layout/LineLength:
  Max: 100

Layout/IndentationStyle:
  EnforcedStyle: spaces

Layout/IndentationWidth:
  Width: 2

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'test/**/*'
