AllCops:
  TargetRubyVersion: 3.1
  NewCops: disable
  Exclude:
    - 'vendor/**/*'

Layout/LineLength:
  Max: 200

Layout/IndentationStyle:
  EnforcedStyle: spaces

Layout/IndentationWidth:
  Width: 2

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 60
  Exclude:
    - 'test/**/*'
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/ClassVars:
  Enabled: false

Security/Eval:
  Enabled: false

Security/MarshalLoad:
  Enabled: false

Style/WhileUntilModifier:
  Enabled: false
