language: ruby
cache: bundler

script: 'bundle exec rake test'

rvm:
  - 2.7
  - 3.0
  - 3.1
  - 3.2
  - 3.3
  - ruby-head
  - truffleruby
  - truffleruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: truffleruby-head