# Data
require "ai4r/data/data_set"
require "ai4r/data/statistics"
require "ai4r/data/proximity"
require "ai4r/data/parameterizable"
# Clusterers
require "ai4r/clusterers/clusterer"
require "ai4r/clusterers/k_means"
require "ai4r/clusterers/bisecting_k_means"
require "ai4r/clusterers/single_linkage"
require "ai4r/clusterers/complete_linkage"
require "ai4r/clusterers/average_linkage"
require "ai4r/clusterers/weighted_average_linkage"
require "ai4r/clusterers/centroid_linkage"
require "ai4r/clusterers/median_linkage"
require "ai4r/clusterers/ward_linkage"
require "ai4r/clusterers/diana"
# Classifiers
require "ai4r/classifiers/classifier"
require "ai4r/classifiers/id3"
require "ai4r/classifiers/prism"
require "ai4r/classifiers/one_r"
require "ai4r/classifiers/zero_r"
require "ai4r/classifiers/hyperpipes"
# Neural networks
require "ai4r/neural_network/backpropagation"
require "ai4r/neural_network/hopfield"
# Genetic Algorithms
require "ai4r/genetic_algorithm/genetic_algorithm"
