name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true
      - run: bundle exec rake test
      - run: |
          coverage=$(jq '.result.line' coverage/.last_run.json || echo "unknown")
          echo "Coverage $coverage"
